### ISSUE TITLE
Recherche d'agendas ?

### ISSUE THREAD

**Issue by johndodev** [OpenAgenda/sdk-php#12]
Hello,

Est-ce qu'il est prévu / possible éventuellement d'implémenter la recherche d'agendas dans le SDK ? 

https://developers.openagenda.com/20-lister-les-agendas/

**Comment by kaore** [comment]
@johndodev oui! Ça sera en place d'ici quelques semaines. Très probablement avant la fin du mois.

**Comment by johndodev** [comment]
D'ac merci !
