### ISSUE TITLE
Erreur dans la doc

### ISSUE THREAD

**Issue by johndodev** [OpenAgenda/sdk-php#13]
C'est pas vraiment un problème du SDK, mais il me semble que le schéma à évolué depuis la doc ici : 
https://developers.openagenda.com/00-structure-evenement/#outils-d-inscription
Sur le champ "registration", je crois que chaque clé est un tableau avec un type (link, phone, email, ticketLink).

**Comment by kaore** [comment]
Bonjour @johndodev effectivement, il y a une petite variation sur la structure de la donnée entre les opés de lecture et d'écriture. Nous corrigeons la doc.
